import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import logo from './favicon.png'
const outfit = Outfit({
  subsets: ["latin"], weight : ["400", "500", "600","700"]
});

const ovo = Ovo({
  subsets: ["latin"], weight : ["400"]
});

export const metadata: Metadata = {
  title: "Dr. Prachy Homeopathy",
  description: "Generated by Pooja Jaipal Gailkwad",
  // icons: {
  //   icon: "/favicon.png", // or .png if you prefer
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.png"></link>
      </head>
      <body
        className={`${outfit.className} ${ovo.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
        {children}
        
        </ThemeProvider>
      </body>
    </html>
  );
}
